version: 2
jobs:
   build:
     macos:
       xcode: "9.0"
     steps:
       - checkout
       - run: sh ./build-libssl.sh
       - store_artifacts:
         path: /Users/distiller/project/work/ssl/OpenSSL-for-iPhone/openssl.framework/teste.tar.gz
         destination: teste.tar.gz
