version: 2
jobs:
   build:
     macos:
       xcode: "9.3"
     steps:
       - checkout

       - run: xcodebuild -showsdks

       - run: sh ./build-all.sh

       - store_artifacts:
          path: ~/libssl.tar.gz
          destination: libssl.tar.gz
