version: 2
jobs:
   build:
     macos:
       xcode: "9.0"
     steps:
       - checkout

       - run: sh ./build-libssl.sh

       # - store_artifacts:
       #   path: ~/teste.tar.gz
       #   destination: teste.tar.gz
