version: 2
jobs:
   build:
     macos:
       xcode: "9.0"
     steps:
       - checkout

       - run: sh ./build-libssl.sh

       - store_artifacts:
         path: /libssl.tar.gz
         destination: libssl.tar.gz
